# Generated by Django 3.2.3 on 2023-01-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postdate', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('cooking', '料理'), ('washing dish', '皿洗い'), ('sink drain', 'シンク排水溝'), ('laundry', '洗濯干し'), ('fold', '洗濯たたみ'), ('wash basin', '手洗い場'), ('bath', 'お風呂'), ('toilet', 'トイレ'), ('trash', 'ゴミ出し')], max_length=50)),
                ('username', models.CharField(choices=[('tekate', 'テカテ'), ('emi', 'エミ')], max_length=50)),
                ('suntext', models.TextField()),
            ],
        ),
    ]
