# Generated by Django 3.2.3 on 2023-01-19 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('housework', '0002_alter_houseworkmodel_postdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseworkmodel',
            name='category',
            field=models.CharField(choices=[('cooking', '料理'), ('washing dish', '皿洗い'), ('sink drain', 'シンク排水溝'), ('kitchen', 'キッチン'), ('laundry', '洗濯干し'), ('fold', '洗濯たたみ'), ('wash basin', '手洗い場'), ('bath', 'お風呂'), ('toilet', 'トイレ'), ('trash', 'ゴミ出し'), ('floor', '床掃除')], max_length=50, verbose_name='家事'),
        ),
        migrations.AlterField(
            model_name='houseworkmodel',
            name='postdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='houseworkmodel',
            name='suntext',
            field=models.TextField(verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='houseworkmodel',
            name='username',
            field=models.CharField(choices=[('tekate', 'テカテ'), ('emi', 'エミ')], max_length=50, verbose_name='担当者'),
        ),
    ]
