# Generated by Django 3.2.3 on 2023-01-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housework', '0004_alter_houseworkmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseworkmodel',
            name='category',
            field=models.CharField(choices=[('cooking', '料理'), ('washing dish', '皿洗い'), ('kitchen', 'キッチン'), ('sink drain', 'シンク排水溝'), ('laundry', '洗濯干し'), ('fold', '洗濯たたみ'), ('wash basin', '手洗い場'), ('bath', 'お風呂'), ('toilet', 'トイレ'), ('trash', 'ゴミ出し'), ('floor', '床掃除')], max_length=50, verbose_name='家事'),
        ),
    ]
